#+TITLE: Authorship

* Response

1. The director, Lee Daniels, is an author of the film—the trailer explicitly gives credit to him. The director has the most control over how the film looks and sounds. They make important decisions about all aspects of the film including mise-en-scene, cinematography, editing, sound, etc. You can usually tell if a film was made by a certain director since they tend to direct films in a similar style. They are also used as a form of marketing a film, for example, in the trailer they mention how Daniels is the director for the film “Precious”—implying that people who have seen that film would like this film too.

2. The writer, Danny Strong, is an author of the film—the trailer explicitly gives credit to him. The writer defines the story and plot points of the film. They make important decisions on the narrative of the film. In the case of this film, the writer authored the story of a butler working at the White House.

3. The actors, Forest Whitaker, Oprah Winfrey, John Cusack, Jane Fonda, Cuba Gooding Jr., Terrence Howard, Lenny Kravitz, James Marsden, David Oyelowo, Vanessa Redgrave, Alan Rickman, Liev Schreiber, Robin Williams, and others not explicitly mentioned in the trailer, are authors of the film. The actors act as different characters in the film. They contribute to the mise-en-scene of the film in the human figure aspect through their talent, performance, visual appeal, etc.

4. The casting director is a possible author of the film. The casting director makes important decisions about which actors will be cast for the film. They have to know whether a person is fit for a particular role or not. They contribute to the mise-en-scene of the film in the human figure aspect by selecting and coordinating the people who will be seen on screen (i.e., the actors). In the case of this film, the casting director decided that actors such as Forest Whitaker and Oprah Winfrey were best fit for the roles in this film.

5. The sound technician is a possible author of the film. The sound technician contributes to the sound of the film. The sound technician controls what the audience hears during a film. In the case of this trailer, the sound technician may control the volume of all the different sounds being heard at any given point, for example.
