#+TITLE: Editing

1. How many shots in the sequence? (I will allow + or - 2.)

  I counted 56 different shots.
  It was very hard to keep track of.

2. Cite one specific example of how cinematography is working with the editing in the clip.

  In the sequence of big close-up shots between what appears to be an intense lecture between a teacher and his student, the editing cuts rapidly between their faces in a shot/reverse-shot pattern which complements the low-angle shots of the teacher and high-angle shots of the student emphasizing the teacher's frustration and the resembling the student's heartbeat as he is feeling increasing pressure.

3. Identify a component of mise-en-scene and explain its function.

   At 2:13 we see that the student has joined with the rest of his band however the composition shows him sitting low among the rest of his bandmates who are either standing or sitting up straight in the mid-ground against a dimly lit wall in the background with many musical instruments in the foreground.
   This composition makes him look small compared to everyone else as they are playing music and giving the audience a sense that he is the only band member who doesn't know what they are doing and that he is a letdown for the team whereas the others are playing music normally.

4. Explain whether the editing is continuous or discontinuous.

   The editing is discontinuous as it breaks the 180 degree rule.
