#+TITLE: Final Exam

* Question 2

** Question

Who or what would you argue to be the author of this film and who will be its audience?
What is the relationship between the two?
Be sure to explain your answer and when you do, account for the ideal audience/reader, the implied audience/reader, and the possible actual readers.
Use evidence from the trailer to support your points and your knowledge of how authorship works with film.

** Response

In the trailer for "The Fabelmans", we see that Steven Spielberg is the author of the film---the trailer very clearly emphasizes this fact by showing "FROM DIRECTOR STEVEN SPIELBERG" in the middle of the clip.
The ideal audience for this film are fans of Steven Spielberg's movies as well as people who are interested in a coming-of-age story about a boy who grows up making movies---the trailer supports this narrative because it shows the boy as a child when he first discovers film, to him as a teen showing his film in a movie theater, to him as a young adult finding love.
The possible actual audiences include people who aren't fans of Steven Spielberg's work or are not interested in coming-of-age stories.
The relationship between Spielberg and his audience in this film is that the Spielberg intends for the audience to read the film specifically as another great Steven Spielberg movie that fans will enjoy as well as a great story about the coming-of-age of a filmmaker.
For the ideal reader, they will interpret the film closely to Spielberg---as just another great Spielberg film and/or as a pleasant story about the coming-of-age of a filmmaker.
However, the actual reader who may not be familiar with or is not a fan of Spielberg's work, may have a different interpretation of the film.
For example, the actual reader may hold very strong opinions on diversity in movies and may be critical of the lack of diversity in the cast of this film---in this trailer, we only see white actors.

* Question 3

** Question

How is this film part of a particular social context?
How might this film be relevant today and how might it be relevant ten or twenty years from now?
When you are responding to this question, you want to be sure to identify the film in its overall context (the events of the period) and think about it as being part of a particular historical context.

** Response

In the trailer for "ALL THE BEAUTY AND THE BLOODSHED", we can tell that the film is part of a social context because its narrative of an evil, greedy pharma company is clearly influenced by current/past events of death and destruction as cited by the activists shown in the trailer.
This film is relevant today as it shows audiences the current state of social issues regarding drug epidemics in today's world and shows why people should stand up to big pharma companies who profit from the addiction and death of drug users.
This film may be relevant ten or twenty years from now because it can act as reference for what the drug epidemic was like in 2020's compared to what it is like in the 2030's or 2040's and allow us to measure our progress on the social issue.

* Question 4

** Question

What role is the film star (or stars) playing in this trailer?
Who would you consider to be the “biggest” star and why?
Use evidence from the trailer to support your points and make a connection between stardom, the film itself, and the film’s apparent ideology.

** Response

In the trailer for "Ticket to Paradise", the film stars, George Clooney and Julia Roberts, play the role of a divorced couple who are trying to prevent their daughter Lily from marrying a guy named Gede so that she doesn't throw her career away.
Based on the trailer, the biggest stars in this film would be George Clooney and Julia Roberts because (1) they are the most famous people in the film as their names are shown in large font at the end of the trailer, (2) they appear to be a focal point of the mise-en-scene as shown by their dominant figure placement in each shot, and (3) they are both riding in first class to Bali which emphasizes their wealth and fame and indicates an apparent capitalistic ideology of the film.

* Question 6

** Question

Examine the clip below and account for its mise-en-scene, cinematography, editing, and sound.
Which technique stands out the most and how does it contribute to the overall narrative of the clip?
How would that narrative change if that same technique was altered?  Note: for this response, you will want to provide specifics (as you did in the quizzes).
And what ideological investment does the clip seem to be most invested?

** Response

In the trailer for "Knock at the Cabin", the sound stands out the most and contributes to the overall apocalypse narrative of the clip by distinguishing the carefree, happy pre-apocalypse "American Dream" life through the use of diegetic upbeat American music and singing as opposed to the serious and stressful apocalypse life indicated by the eerie non-diegetic ringing sounds and harsh door knocking sounds which make the audience perceive the film as a horror film.
If the sound was altered to be all upbeat, happy music, for example, then the audience may perceive the film as a comedy film or similar genre instead.
This clip seems to be most invested in the ideology of the American Dream and that people can decide either to continue pursue the American Dream or save the rest of the world---this is emphasized by the on-screen text "MAKE THE CHOICE" at the end of the trailer.

* Study Guide

** Details

The exam has six (6) questions relating to some selected film trailers.
Write responses to four (4) of them.
25 points each.
Be sure to substantiate your assertions in coherent, well-developed points that employ the terms and concepts with which we have been working.
Concentrate on scenes from each clip as illustrations of, and evidence for, your assertions.
I will be looking for a strong command of the terms and concepts with which we have been working and specifics from the clips that support your points.

** Questions

1) Why would a studio back the production of this film?
   Is it a good gamble or not?
   Does it look to be similar to or different from other films that have made money?
   With your answers to these questions in mind, you will want to use the concept of ideology to discuss the trailer’s critical, compliant, or contradictory attitude toward dominant ideology (the “status quo”).

2) Who or what would you argue to be the author of this film and who will be its audience?
   What is the relationship between the two?
   Be sure to explain your answer and when you do, account for the ideal audience/reader, the implied audience/reader, and the possible actual readers.
   Use evidence from the trailer to support your points and your knowledge of how authorship works with film.

3) How is this film part of a particular social context?
   How might this film be relevant today and how might it be relevant ten or twenty years from now?
   When you are responding to this question, you want to be sure to identify the film in its overall context (the events of the period) and think about it as being part of a particular historical context.

4) What role is the film star (or stars) playing in this trailer?
   Who would you consider to be the “biggest” star and why?
   Use evidence from the trailer to support your points and make a connection between stardom, the film itself, and the film’s apparent ideology.

5) Develop a response that accounts for a classification system you would use for this trailer.
   What evidence would you use to support a general paradigm for the trailer?
   Which characteristics of this genre are most apparent in the trailer and which are least apparent?

6) Examine the clip below and account for its mise-en-scene, cinematography, editing, and sound.
   Which technique stands out the most and how does it contribute to the overall narrative of the clip?
   How would that narrative change if that same technique was altered?  Note: for this response, you will want to provide specifics (as you did in the quizzes).
   And what ideological investment does the clip seem to be most invested?
