#+TITLE: Mise-en-Scène Examples

* Citizen Kane

Foreground:
- Dark clothing
- Formal clothing
- Contract

Midground:
- Concerned expression
- Working-class clothing

Background:
- Window frame--separate
- Lone boy

Interpretation:
In this shot from Citizen Kane (Welles, 1941), the mise-en-scene is used to show the relationships between the characters.
There are four characters: two in the foreground, one in the mid-ground, and one, a boy, in the background.
From this placement we can assume that the three adults are discussing the boy.
The window frame accentuates the fact that the boy is outside and isn't a part of the decisions being made about him.
The clothing and placement of the adults indicates that the two in the foreground, with their dark, formal attire, are in control of the situation more than the man in lighter, working clothing.
This is also reflected through facial expressions, as the working man looks concerned, while the woman has a determined, firm expression.
Finally, the document being signed in the foreground shows its importance and that their decision is final and official.
Overall, the mise-en-scene shows that the boy's fate is out of his hands as adults inside make serious and concerning decisions about his future.

* Breakfast Club

1. Initial shots of the inside of the school---large ticking clock on the top of the wall; large canteen with soda machines, cups and snacks; and rows of lockers in large hallway with one locker vandalized---implies the feeling of what high school was like for most people in the United States.

2. Brutalist school design with a dark, gloomy, and uninviting entrance and no people around---implies that it's outside school hours and it's not the place people want to be right now, i.e., it resembles a prison.

3. Pristine, shiny BMW; driver is a man who's well dressed in clean, dark suit, white shirt, and patterned scarf around his neck, with brown groomed hair, and the passenger is a woman who's also well dressed with a leater jacket, diamond earings and also has brown groomed hair with nice makeup---this implies that the woman is the princess and the man is her father who's dropping her off at the school.

4. Red, blocky car with "EMC 2" driver's license; driver is a woman who's in a large dark coat and the passengers are a small girl wearing a red coat and a boy wearing a dark coat and orange/blue beanie---this implies that the boy is the "brain" and the woman is his mom dropping him off at the school while the little girl is his younger sister.

* Quiz

1. Gir

2.

3.

4.


The four components of mise-en-scene are setting, lighting, human figures, and composition.

1) At the shot (0:42) with the horse in the open park, it is day time; the tree's leaves seem to be dying as the branches are becoming bare and there are leaves scattered across the land. This setting implies that we are approaching winter time.

2) In the same shot, we see that there are some objects in the scene which are not very well lit, including the trees, the characters, and the horse. Meanwhile, the ground is well lit, clearly showing that it has different shades of green and brown. The ground being lit implies a sense of peacefulness and the fact that the characters are not lit up in this scene imply that they are leaving these peaceful grounds.

3) In this clip, we see several characters of interest including, the most important one---the woman introduced at the very beginning (0:28), a helper (0:42), a child (1:19), and many characters helping the woman by the seashore (3:22). The woman has well groomed, shiny hair and is dressed in a conservative, old-fashioned manner with a large, dark dress covering her entire body and a headpiece with a dark exterior, but white interior. The young girl, maybe 10 years old, is sleeping in a sizable bed with large, white sheets and pillows covering her body however with her shoes exposed to reveal that the woman is attaching wheels to the girl's shoes. This implies that there is a guardian-child relationship between the woman and the girl and that the woman is trying to take care of the girl. 

4) 
* Hello
The four components of mise-en-scene are setting, lighting, human figures, and composition.

1) At the shot (0:42) with the horse in the open park, it is day time; the tree's leaves seem to be dying as the branches are becoming bare and there are leaves scattered across the land. This setting implies that we are approaching winter time.

2) In the same shot, we see that there are some objects in the scene which are not very well lit, including the trees, the characters, and the horse. Meanwhile, the ground is well lit, clearly showing that it has different shades of green and brown. The ground being lit implies a sense of peacefulness and the fact that the characters are not lit up in this scene imply that they are leaving these peaceful grounds.

3) In this clip, we see several characters of interest including, the most important one---the woman introduced at the very beginning (0:28), a helper (0:42), a child (1:19), and many characters helping the woman by the seashore (3:22). The woman has well groomed, shiny hair and is dressed in a conservative, old-fashioned manner with a large, dark dress covering her entire body and a headpiece with a dark exterior, but white interior. The young girl, maybe 10 years old, is sleeping in a sizable bed with large, white sheets and pillows covering her body however with her shoes exposed to reveal that the woman is attaching wheels to the girl's shoes. This implies that there is a guardian-child relationship between the woman and the girl and that the woman is trying to take care of the girl. 

4) The composition is most apparent in the last section of the clip with the seashore (3:44), where in the foreground are the characters by the seashore with the woman, in the mid-ground is the boat, and in the background is the sea with many waves crashing in. This composition implies that the woman and other characters are stuck on a new place and will have to seek refuge in the place that they've found themselves in.
