#+TITLE: Narrative

* Question 1

Based on the trailer, this film clearly falls into the romance genre.
The trailer gives the plot points out quite clearly:

- A: Boy meets girl
- B: They break up
- C: They get back together and live happily ever after

The totality of these plot points gives a story which is what I would expect from a romance film.

* Question 2

Based on the trailer, this film looks like it will be a linear/classic narrative since the trailer goes through the story in chronological order starting from Day 1 to Day 500, as shown in the non-diegetic text between each scene.
Additionally, the order of the scenes make sense according to the romance genre which suggests linearity of narrative.

* Question 3

A film's plot is how its story unfolds, in other words, the sequence of scenes in the film.
In the case of the trailer, the sequence of scenes are:

- Boy meets girl in elevator when she tells him that she loves the artist that he's listening to.

- FOX searchlight.

- Alternating video on the left and right sides of the screen, capturing the boy and girl's lives growing up, in parallel.

- Introduction of the boy as Tom Hansen, in a conference room at his office job.

- Introduction of the girl as Summer Finn, in the same office building but in a different room.

- Tom and Summer romantically holding hands outside on a bench.

- Summer breaks up with Tom.

- Tom talks with his younger siblings about the break up.

* Question 4

Based on the trailer, it seems that the story is a love story between Tom and Summer, where they break up and Tom tries to get back with her.
