#+TITLE: Sound Quiz


* Questions

1. What types of sounds are present and are they diegetic or nondiegetic? Name at least 5.

2. Take one of the sounds listed above and describe its overall function and how it helps create meaning in the clip.

3. Explain how another sound accentuates and strengthens the visual image.

4. How is another sound working with one of the major components of cinema (major components = what we have been studying)?

* Answers

** Question 1

- Thumping in the background: diegetic

- Character breathing: diegetic

- Table sliding on the floor: diegetic

- Drugs spilling on the floor: diegetic

- Door squeaking: diegetic

- Birds chirping: diegetic

- High-pitched ringing: nondiegetic

- Girl laughing: diegetic

- Water splashing: diegetic

- Mirror wipe: diegetic

- Character dialogue: diegetic

- Basketball bouncing: diegetic

- Happy, upbeat background music: nondiegetic

** Question 2

The high-pitched ringing that starts at 1:45 which fades away at 2:05 (20 seconds long) helps understand the character's state of mind: she's in a very fuzzy, dizzy mindset which gives the sense that the drugs introduced in the beginning of the clip are having an effect on her.

** Question 3

The nondiegetic sound of the happy, upbeat background music at the end of the clip greatly contrasts the visual image of the blood-covered house and blood-covered car.
Without the music, I would feel very on edge and suspicious of the female character; however with the music, I feel more relaxed and comfortable watching this scene despite the extreme visuals.

** Question 4

The diegetic sound of birds chirping in the background from 0:47 to 1:15 indicate a sunny day with good weather.
This sound complements the mise-en-scene of the typical sunny, suburban environment in establishing the film world and giving a sense that it's just another day in the suburbs.
